### ISSUE TITLE
Nonexistent key leads to Error::BufferSize instead of Error::NotFound

### ISSUE THREAD

**Issue by danielzfranklin** [bbqsrc/registry-rs#2]
First off, thank you for this library. I've done a tiny bit of programming against the raw api bindings, and this is so much more friendly.

If I attempt to get the value of a key that does not exist I get an `value::Error::BufferSize` with a `source.kind()` of `ErrorKind::NotFound`. I expected to get an `value::Error::NotFound` instead.

**Comment by bbqsrc** [comment]
Fixed in v1.1.1. Thanks!
